"""call_score is categorical not numeric

Revision ID: 300f13f0d7b8
Revises: a6c44c126771
Create Date: 2026-08-07 16:13:52.188191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300f13f0d7b8'
down_revision: Union[str, Sequence[str], None] = 'a6c44c126771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis', 'call_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis', 'call_score',
               existing_type=sa.String(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
