"""call_storage input gate exclusion columns

Revision ID: 97a75d1d0ced
Revises: 7f1c9a2b4de3
Create Date: 2026-08-13 14:56:42.570272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a75d1d0ced'
down_revision: Union[str, Sequence[str], None] = '7f1c9a2b4de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_storage', sa.Column('excluded_reason', sa.String(), nullable=True))
    op.add_column('call_storage', sa.Column('excluded_detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_storage', 'excluded_detail')
    op.drop_column('call_storage', 'excluded_reason')
    # ### end Alembic commands ###
