"""initial tables

Revision ID: a6c44c126771
Revises: 
Create Date: 2026-08-07 16:08:23.235583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6c44c126771'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autofill_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autofill_requests_card_id'), 'autofill_requests', ['card_id'], unique=False)
    op.create_table('call_storage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('avoma_recording_id', sa.String(), nullable=False),
    sa.Column('client_record_id', sa.String(), nullable=False),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('call_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_storage_avoma_recording_id'), 'call_storage', ['avoma_recording_id'], unique=True)
    op.create_index(op.f('ix_call_storage_client_record_id'), 'call_storage', ['client_record_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('call_type', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_prompt_versions_content_hash')
    )
    op.create_index(op.f('ix_prompt_versions_kind'), 'prompt_versions', ['kind'], unique=False)
    op.create_table('analysis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('avoma_recording_id', sa.String(), nullable=False),
    sa.Column('call_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('call_type', sa.String(), nullable=True),
    sa.Column('risk_gap_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('card_type', sa.String(), nullable=True),
    sa.Column('scoring_prompt_version_id', sa.BigInteger(), nullable=True),
    sa.Column('gap_rubric_version_id', sa.BigInteger(), nullable=True),
    sa.Column('card_type_prompt_version_id', sa.BigInteger(), nullable=True),
    sa.Column('call_type_status', sa.String(), nullable=False),
    sa.Column('scoring_status', sa.String(), nullable=False),
    sa.Column('gap_status', sa.String(), nullable=False),
    sa.Column('card_type_status', sa.String(), nullable=False),
    sa.Column('call_type_error', sa.Text(), nullable=True),
    sa.Column('scoring_error', sa.Text(), nullable=True),
    sa.Column('gap_error', sa.Text(), nullable=True),
    sa.Column('card_type_error', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('dead_letter_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_type_prompt_version_id'], ['prompt_versions.id'], ),
    sa.ForeignKeyConstraint(['gap_rubric_version_id'], ['prompt_versions.id'], ),
    sa.ForeignKeyConstraint(['scoring_prompt_version_id'], ['prompt_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_avoma_recording_id'), 'analysis', ['avoma_recording_id'], unique=True)
    op.create_index(op.f('ix_analysis_status'), 'analysis', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_status'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_avoma_recording_id'), table_name='analysis')
    op.drop_table('analysis')
    op.drop_index(op.f('ix_prompt_versions_kind'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_call_storage_client_record_id'), table_name='call_storage')
    op.drop_index(op.f('ix_call_storage_avoma_recording_id'), table_name='call_storage')
    op.drop_table('call_storage')
    op.drop_index(op.f('ix_autofill_requests_card_id'), table_name='autofill_requests')
    op.drop_table('autofill_requests')
    # ### end Alembic commands ###
