"""per-step retry counters

Gives each analyser step its own retry budget. `analysis.retry_count` is
row-level and shared, so a failure in one step permanently consumed every other
step's chances: a call whose four steps each failed once or twice on different
nights got dead-lettered while no individual step had exhausted anything.

`retry_count` is kept as "how many passes this row has had" for observability;
escalation to failed_permanent now reads these columns instead.

server_default '0' so the rows written before this exist with a full budget
rather than NULL. That is a one-time reset of their (shared, unfair) count,
which is harmless — they are all `processed`.

Revision ID: cddcbee4eb25
Revises: b8b6bf4743ec
Create Date: 2026-08-10 21:01:50.970593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cddcbee4eb25'
down_revision: Union[str, Sequence[str], None] = 'b8b6bf4743ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('call_type_retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('analysis', sa.Column('scoring_retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('analysis', sa.Column('gap_retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('analysis', sa.Column('card_type_retry_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'card_type_retry_count')
    op.drop_column('analysis', 'gap_retry_count')
    op.drop_column('analysis', 'scoring_retry_count')
    op.drop_column('analysis', 'call_type_retry_count')
    # ### end Alembic commands ###
