"""analysis.call_score_categories: the subscores behind the tier

Revision ID: e74f5a5b804e
Revises: 97a75d1d0ced
Create Date: 2026-08-13 20:07:24.363688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e74f5a5b804e'
down_revision: Union[str, Sequence[str], None] = '97a75d1d0ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('call_score_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'call_score_categories')
    # ### end Alembic commands ###
